/**
 * Generates environment.prod.ts from NG_APP_API_URL before the Netlify build.
 */
const fs = require('fs');
const path = require('path');

const DEFAULT_API_URL = '/api/v1';
const apiUrl = process.env.NG_APP_API_URL || process.env.API_PUBLIC_URL || DEFAULT_API_URL;

const content = `/** Auto-generated by scripts/generate-env.js — do not edit manually in CI */
export const environment = {
  production: true,
  apiUrl: '${apiUrl.replace(/'/g, "\\'")}',
  siteName: 'Zaninettis',
};
`;

const out = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(out, content, 'utf8');
console.log('Wrote environment.prod.ts with apiUrl:', apiUrl);
